// Generated by dia2code
#ifndef STATE__ABILITY__H
#define STATE__ABILITY__H

#include <memory>
#include <vector>

namespace state {
  class GameElement;
  class PlayableGameElement;
}

#include "GameElement.h"
#include "PlayableGameElement.h"

namespace state {

  // Interface
  /// class Ability - 
  class Ability : public state::GameElement {
    // Associations
    // Attributes
  public:
    std::shared_ptr<GameElement> source;
    std::vector<std::weak_ptr<PlayableGameElement>> targets;
    // Operations
  public:
    void Resolve ();
    bool ValidTargets ();
    void Copy ();
    // Setters and Getters
  };

};

#endif
