// Generated by dia2code
#ifndef STATE__ACTIVATEDABILITY__H
#define STATE__ACTIVATEDABILITY__H


namespace state {
  class Ability;
}

#include "Ability.h"

namespace state {

  /// class ActivatedAbility - 
  class ActivatedAbility : public state::Ability {
    // Operations
  public:
    ActivatedAbility ();
    ~ActivatedAbility ();
    // Setters and Getters
  };

};

#endif
