// Generated by dia2code
#ifndef STATE__BATTLEFIELD__H
#define STATE__BATTLEFIELD__H

#include <list>
#include <memory>

namespace state {
  class Zone;
  class Permanent;
  class Game;
}

#include "Zone.h"
#include "Permanent.h"
#include "Game.h"

namespace state {

  /// class Battlefield - 
  class Battlefield : public state::Zone {
    // Associations
    // Attributes
  public:
    std::list<std::shared_ptr<Permanent>> battlefieldContent;
    // Operations
  public:
    Battlefield ();
    ~Battlefield ();
    // Setters and Getters
  };

};

#endif
