// Generated by dia2code
#ifndef STATE__CARDPERMANENT__H
#define STATE__CARDPERMANENT__H

#include <memory>

namespace state {
  class Card;
  class Permanent;
}

#include "Card.h"
#include "Permanent.h"

namespace state {

  /// class CardPermanent - 
  class CardPermanent : public state::Permanent, public state::Card {
    // Attributes
  public:
    std::shared_ptr<Card> card;
    // Operations
  public:
    CardPermanent ();
    ~CardPermanent ();
    // Setters and Getters
  };

};

#endif
