// Generated by dia2code
#ifndef STATE__CARD__H
#define STATE__CARD__H

#include <string>

namespace state {
  class Cost;
  class PlayableGameElement;
  class CardZone;
}

#include "Cost.h"
#include "PlayableGameElement.h"
#include "CardZone.h"

namespace state {

  /// class Card - 
  class Card : public state::PlayableGameElement {
    // Associations
    // Attributes
  public:
    std::string name;
    Cost cost;
    std::string image_uri;
    // Operations
  public:
    Card ();
    ~Card ();
    // Setters and Getters
  };

};

#endif
