// Generated by dia2code
#ifndef STATE__CARDZONE__H
#define STATE__CARDZONE__H

#include <vector>
#include <memory>

namespace state {
  class Card;
  class Zone;
}

#include "Card.h"
#include "Zone.h"

namespace state {

  // interface
  /// class CardZone - 
  class CardZone : public state::Zone {
    // Attributes
  public:
    std::vector<std::shared_ptr<Card>> cards;
    // Operations
  public:
    void PutOnTheBattlefield (std::weak_ptr<Card> card);
    std::weak_ptr<Card> GetCard (int position);
    std::vector<std::weak_ptr<Card>> GetCards ();
    // Setters and Getters
  };

};

#endif
