// Generated by dia2code
#ifndef STATE__COMMAND__H
#define STATE__COMMAND__H


namespace state {
  class Zone;
  class Game;
}

#include "Zone.h"
#include "Game.h"

namespace state {

  /// class Command - 
  class Command : public state::Zone {
    // Associations
    // Operations
  public:
    Command ();
    ~Command ();
    // Setters and Getters
  };

};

#endif
