// Generated by dia2code
#ifndef STATE__COST__H
#define STATE__COST__H

#include <list>

namespace state {
  class Mana;
}

#include "Mana.h"

namespace state {

  /// class Cost - 
  class Cost {
    // Attributes
  public:
    std::list<Mana> manas;
    // Operations
  public:
    Cost ();
    ~Cost ();
    // Setters and Getters
  };

};

#endif
