// Generated by dia2code
#ifndef STATE__EXILE__H
#define STATE__EXILE__H


namespace state {
  class CardZone;
  class Game;
}

#include "CardZone.h"
#include "Game.h"

namespace state {

  /// class Exile - 
  class Exile : public state::CardZone {
    // Associations
    // Operations
  public:
    Exile ();
    ~Exile ();
    // Setters and Getters
  };

};

#endif
