// Generated by dia2code
#ifndef STATE__GAMEELEMENT__H
#define STATE__GAMEELEMENT__H


namespace state {
  class IObservable;
}

#include "IObservable.h"

namespace state {

  // "Interface"
  /// class GameElement - things that can be targetted
  class GameElement : public state::IObservable {
    // Setters and Getters
  };

};

#endif
