// Generated by dia2code
#ifndef STATE__GAMEELEMENT__H
#define STATE__GAMEELEMENT__H


namespace state {

  // "Interface"
  /// class GameElement - things that can be targetted
  class GameElement {
    // Setters and Getters
  };

};

#endif
