// Generated by dia2code
#ifndef STATE__GRAVEYARD__H
#define STATE__GRAVEYARD__H


namespace state {
  class CardZone;
  class Player;
}

#include "CardZone.h"
#include "Player.h"

namespace state {

  /// class Graveyard - 
  class Graveyard : public state::CardZone {
    // Associations
    // Operations
  public:
    Graveyard ();
    ~Graveyard ();
    // Setters and Getters
  };

};

#endif
