// Generated by dia2code
#ifndef STATE__HAND__H
#define STATE__HAND__H


namespace state {
  class CardZone;
  class Player;
}

#include "CardZone.h"
#include "Player.h"

namespace state {

  /// class Hand - 
  class Hand : public state::CardZone {
    // Associations
    // Attributes
  private:
    int maximumHandSize     = 7;
    int startingHandSize     = 7;
    // Operations
  public:
    Hand ();
    ~Hand ();
    // Setters and Getters
  };

};

#endif
