// Generated by dia2code
#ifndef STATE__LIBRARY__H
#define STATE__LIBRARY__H


namespace state {
  class CardZone;
  class Player;
}

#include "CardZone.h"
#include "Player.h"

namespace state {

  /// class Library - 
  class Library : public state::CardZone {
    // Associations
    // Operations
  public:
    Library ();
    ~Library ();
    // Setters and Getters
  };

};

#endif
