// Generated by dia2code
#ifndef STATE__MANA__H
#define STATE__MANA__H

#include <string>

namespace state {
  class Cost;
  class ManaPool;
}

#include "Cost.h"
#include "ManaPool.h"

namespace state {

  /// class Mana - 
  class Mana {
    // Associations
    // Attributes
  public:
    std::string color;
    int amout;
    // Operations
  public:
    Mana ();
    ~Mana ();
    // Setters and Getters
  };

};

#endif
