// Generated by dia2code
#ifndef STATE__MANAABILITY__H
#define STATE__MANAABILITY__H


namespace state {
  class ActivatedAbility;
}

#include "ActivatedAbility.h"

namespace state {

  /// class ManaAbility - 
  class ManaAbility : public state::ActivatedAbility {
    // Operations
  public:
    ManaAbility ();
    ~ManaAbility ();
    // Setters and Getters
  };

};

#endif
