// Generated by dia2code
#ifndef STATE__MANAPOOL__H
#define STATE__MANAPOOL__H

#include <list>

namespace state {
  class Mana;
}

#include "Mana.h"

namespace state {

  /// class ManaPool - 
  class ManaPool {
    // Attributes
  public:
    std::list<Mana> manas;
    // Operations
  public:
    ManaPool ();
    ~ManaPool ();
    // Setters and Getters
  };

};

#endif
