// Generated by dia2code
#ifndef STATE__PLAYABLEGAMEELEMENT__H
#define STATE__PLAYABLEGAMEELEMENT__H

#include <string>
#include <set>
#include <memory>

namespace state {
  class Zone;
  class GameElement;
}

#include "Zone.h"
#include "GameElement.h"

namespace state {

  // "Interface"
  /// class PlayableGameElement - 
  class PlayableGameElement : public state::GameElement {
    // Attributes
  public:
    std::string color;
    int cmc;
    std::set<std::string> types;
    // Operations
  public:
    virtual void MoveTo (std::weak_ptr<Zone> zone) = 0;
    // Setters and Getters
  };

};

#endif
