// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <memory>
#include <list>

namespace state {
  class Graveyard;
  class Library;
  class Hand;
  class Card;
  class PlayableGameElement;
  class GameElement;
  class Game;
}

#include "Graveyard.h"
#include "Library.h"
#include "Hand.h"
#include "Card.h"
#include "PlayableGameElement.h"
#include "GameElement.h"
#include "Game.h"

namespace state {

  /// class Player - 
  class Player : public state::GameElement {
    // Associations
    // Attributes
  private:
    std::shared_ptr<Graveyard> graveyard;
    std::shared_ptr<Library> library;
    std::shared_ptr<Hand> hand;
    // Operations
  public:
    int mana ();
    int manaMax ();
    bool Cast (std::weak_ptr<Card> card);
    bool Play (std::weak_ptr<Card> card);
    bool ActivateAbility (std::weak_ptr<PlayableGameElement> source);
    void PassPriority ();
    bool Draw (int nb);
    bool Discard (int nb);
    std::list<std::weak_ptr<GameElement>> Target ();
    bool Win ();
    bool Lose ();
    std::weak_ptr<Graveyard> GetGraveyard ();
    std::weak_ptr<Library> GetLibrary ();
    std::weak_ptr<Hand> GetHand ();
    Player ();
    ~Player ();
    // Setters and Getters
  };

};

#endif
