// Generated by dia2code
#ifndef STATE__PLAYABLEGAMEELEMENT__H
#define STATE__PLAYABLEGAMEELEMENT__H

#include <string>
#include <set>

namespace state {
  class GameElement;
}

#include "GameElement.h"

namespace state {

  // "Interface"
  /// class PlayableGameElement - 
  class PlayableGameElement : public state::GameElement {
    // Attributes
  public:
    std::string color;
    int cmc;
    std::set<std::string> types;
    // Setters and Getters
  };

};

#endif
