// Generated by dia2code
#ifndef STATE__SPELL__H
#define STATE__SPELL__H


namespace state {
  class Card;
  class Ability;
}

#include "Card.h"
#include "Ability.h"

namespace state {

  /// class Spell - 
  class Spell : public state::Card, public state::Ability {
    // Attributes
  public:
    bool copy;
    // Operations
  public:
    Spell ();
    ~Spell ();
    // Setters and Getters
  };

};

#endif
