// Generated by dia2code
#ifndef STATE__TOKEN__H
#define STATE__TOKEN__H


namespace state {
  class Permanent;
}

#include "Permanent.h"

namespace state {

  /// class Token - 
  class Token : public state::Permanent {
    // Operations
  public:
    Token ();
    ~Token ();
    // Setters and Getters
  };

};

#endif
