// Generated by dia2code
#ifndef STATE__TRIGGEREDABILITY__H
#define STATE__TRIGGEREDABILITY__H


namespace state {
  class Ability;
}

#include "Ability.h"

namespace state {

  /// class TriggeredAbility - 
  class TriggeredAbility : public state::Ability {
    // Operations
  public:
    TriggeredAbility ();
    ~TriggeredAbility ();
    // Setters and Getters
  };

};

#endif
