// Generated by dia2code
#ifndef STATE__ZONE__H
#define STATE__ZONE__H


namespace state {
  class IObservable;
}

#include "IObservable.h"

namespace state {

  // "Interface"
  /// class Zone - 
  class Zone : public state::IObservable {
    // Setters and Getters
  };

};

#endif
