// Generated by dia2code
#ifndef RENDER__PERMANENTRENDERER__H
#define RENDER__PERMANENTRENDERER__H

#include <memory>
#include <SFML/Graphics.hpp>

namespace state {
  class Permanent;
};
namespace sf {
  class Sprite;
}

#include "state/Permanent.h"

namespace render {

  /// class PermanentRenderer - 
  class PermanentRenderer : public sf::Sprite {
    // Operations
  public:
    PermanentRenderer (std::weak_ptr<state::Permanent> permanent);
    // Setters and Getters
  };

};

#endif
