// Generated by dia2code
#ifndef __TURN__H
#define __TURN__H

#include "turn/Step.h"
#include "turn/Phase.h"
#include "turn/Turn.h"
#include "turn/UntapStep.h"
#include "turn/UpkeepStep.h"
#include "turn/DrawStep.h"
#include "turn/BeginningPhase.h"
#include "turn/PrecombatMainPhase.h"
#include "turn/EndOfCombatStep.h"
#include "turn/CombatDamageStep.h"
#include "turn/FirstStrikeCombatDamageStep.h"
#include "turn/DeclareBlockersStep.h"
#include "turn/DeclareAttackersStep.h"
#include "turn/BeginningOfCombatStep.h"
#include "turn/CombatPhase.h"
#include "turn/PostcombatMainPhase.h"
#include "turn/CleanupStep.h"
#include "turn/EndStep.h"
#include "turn/EndingPhase.h"
#endif
