// Generated by dia2code
#ifndef CLIENT__TEST__H
#define CLIENT__TEST__H


namespace render {
  class RenderingManager;
};
namespace state {
  class Game;
}

#include "render/RenderingManager.h"
#include "state/Game.h"

namespace client {

  /// class Test - 
  class Test {
    // Operations
  public:
    void state ();
    void render ();
    void engine ();
    void render_ia ();
    void heuristic_ai ();
    void rollback ();
    void deep_ia ();
    void thread ();
    void record ();
    void play ();
    void listen ();
    void network ();
    // Setters and Getters
  };

};

#endif
