// Generated by dia2code
#ifndef TURN__BEGINNINGOFCOMBATSTEP__H
#define TURN__BEGINNINGOFCOMBATSTEP__H


namespace turn {
  class Step;
}

#include "Step.h"

namespace turn {

  /// class BeginningOfCombatStep - 
  class BeginningOfCombatStep : public turn::Step {
    // Operations
  public:
    BeginningOfCombatStep ();
    ~BeginningOfCombatStep ();
    // Setters and Getters
  };

};

#endif
