// Generated by dia2code
#ifndef TURN__BEGINNINGPHASE__H
#define TURN__BEGINNINGPHASE__H


namespace turn {
  class Phase;
  class UntapStep;
  class UpkeepStep;
  class DrawStep;
}

#include "Phase.h"
#include "UntapStep.h"
#include "UpkeepStep.h"
#include "DrawStep.h"

namespace turn {

  /// class BeginningPhase - 
  class BeginningPhase : public turn::Phase {
    // Associations
    // Operations
  public:
    BeginningPhase ();
    ~BeginningPhase ();
    // Setters and Getters
  };

};

#endif
