// Generated by dia2code
#ifndef TURN__CLEANUPSTEP__H
#define TURN__CLEANUPSTEP__H


namespace turn {
  class Step;
}

#include "Step.h"

namespace turn {

  /// class CleanupStep - 
  class CleanupStep : public turn::Step {
    // Operations
  public:
    CleanupStep ();
    ~CleanupStep ();
    // Setters and Getters
  };

};

#endif
