// Generated by dia2code
#ifndef TURN__COMBATDAMAGESTEP__H
#define TURN__COMBATDAMAGESTEP__H


namespace turn {
  class UpkeepStep;
}

#include "UpkeepStep.h"

namespace turn {

  /// class CombatDamageStep - 
  class CombatDamageStep : public turn::UpkeepStep {
    // Operations
  public:
    CombatDamageStep ();
    ~CombatDamageStep ();
    // Setters and Getters
  };

};

#endif
