// Generated by dia2code
#ifndef TURN__COMBATPHASE__H
#define TURN__COMBATPHASE__H


namespace turn {
  class Phase;
  class EndOfCombatStep;
  class CombatDamageStep;
  class FirstStrikeCombatDamageStep;
  class DeclareBlockersStep;
  class DeclareAttackersStep;
  class BeginningOfCombatStep;
}

#include "Phase.h"
#include "EndOfCombatStep.h"
#include "CombatDamageStep.h"
#include "FirstStrikeCombatDamageStep.h"
#include "DeclareBlockersStep.h"
#include "DeclareAttackersStep.h"
#include "BeginningOfCombatStep.h"

namespace turn {

  /// class CombatPhase - 
  class CombatPhase : public turn::Phase {
    // Associations
    // Operations
  public:
    CombatPhase ();
    ~CombatPhase ();
    // Setters and Getters
  };

};

#endif
