// Generated by dia2code
#ifndef TURN__DECLAREBLOCKERSSTEP__H
#define TURN__DECLAREBLOCKERSSTEP__H


namespace turn {
  class Step;
}

#include "Step.h"

namespace turn {

  /// class DeclareBlockersStep - 
  class DeclareBlockersStep : public turn::Step {
    // Operations
  public:
    DeclareBlockersStep ();
    ~DeclareBlockersStep ();
    // Setters and Getters
  };

};

#endif
