// Generated by dia2code
#ifndef TURN__DECLAREATTACKERSSTEP__H
#define TURN__DECLAREATTACKERSSTEP__H


namespace turn {
  class Step;
}

#include "Step.h"

namespace turn {

  /// class DeclareAttackersStep - 
  class DeclareAttackersStep : public turn::Step {
    // Operations
  public:
    DeclareAttackersStep ();
    ~DeclareAttackersStep ();
    // Setters and Getters
  };

};

#endif
