// Generated by dia2code
#ifndef TURN__DRAWSTEP__H
#define TURN__DRAWSTEP__H


namespace turn {
  class Step;
}

#include "Step.h"

namespace turn {

  /// class DrawStep - 
  class DrawStep : public turn::Step {
    // Operations
  public:
    DrawStep ();
    ~DrawStep ();
    // Setters and Getters
  };

};

#endif
