// Generated by dia2code
#ifndef TURN__ENDINGPHASE__H
#define TURN__ENDINGPHASE__H


namespace turn {
  class Phase;
  class CleanupStep;
  class EndStep;
}

#include "Phase.h"
#include "CleanupStep.h"
#include "EndStep.h"

namespace turn {

  /// class EndingPhase - 
  class EndingPhase : public turn::Phase {
    // Associations
    // Operations
  public:
    EndingPhase ();
    ~EndingPhase ();
    // Setters and Getters
  };

};

#endif
