// Generated by dia2code
#ifndef TURN__ENDOFCOMBATSTEP__H
#define TURN__ENDOFCOMBATSTEP__H


namespace turn {
  class Step;
}

#include "Step.h"

namespace turn {

  /// class EndOfCombatStep - 
  class EndOfCombatStep : public turn::Step {
    // Operations
  public:
    EndOfCombatStep ();
    ~EndOfCombatStep ();
    // Setters and Getters
  };

};

#endif
