// Generated by dia2code
#ifndef TURN__ENDSTEP__H
#define TURN__ENDSTEP__H


namespace turn {
  class Step;
}

#include "Step.h"

namespace turn {

  /// class EndStep - 
  class EndStep : public turn::Step {
    // Operations
  public:
    EndStep ();
    ~EndStep ();
    // Setters and Getters
  };

};

#endif
