// Generated by dia2code
#ifndef TURN__FIRSTSTRIKECOMBATDAMAGESTEP__H
#define TURN__FIRSTSTRIKECOMBATDAMAGESTEP__H


namespace turn {
  class Step;
}

#include "Step.h"

namespace turn {

  /// class FirstStrikeCombatDamageStep - 
  class FirstStrikeCombatDamageStep : public turn::Step {
    // Operations
  public:
    FirstStrikeCombatDamageStep ();
    ~FirstStrikeCombatDamageStep ();
    // Setters and Getters
  };

};

#endif
