// Generated by dia2code
#ifndef TURN__PHASE__H
#define TURN__PHASE__H

#include <vector>

namespace turn {
  class Step;
  class Turn;
}

#include "Step.h"
#include "Turn.h"

namespace turn {

  // interface
  /// class Phase - 
  class Phase {
    // Associations
    // Attributes
  public:
    std::vector<Step> steps;
    // Operations
  public:
    virtual void NextStep () = 0;
    // Setters and Getters
  };

};

#endif
