// Generated by dia2code
#ifndef TURN__POSTCOMBATMAINPHASE__H
#define TURN__POSTCOMBATMAINPHASE__H


namespace turn {
  class Phase;
}

#include "Phase.h"

namespace turn {

  /// class PostcombatMainPhase - 
  class PostcombatMainPhase : public turn::Phase {
    // Operations
  public:
    PostcombatMainPhase ();
    ~PostcombatMainPhase ();
    // Setters and Getters
  };

};

#endif
