// Generated by dia2code
#ifndef TURN__PRECOMBATMAINPHASE__H
#define TURN__PRECOMBATMAINPHASE__H


namespace turn {
  class Phase;
}

#include "Phase.h"

namespace turn {

  /// class PrecombatMainPhase - 
  class PrecombatMainPhase : public turn::Phase {
    // Operations
  public:
    PrecombatMainPhase ();
    ~PrecombatMainPhase ();
    // Setters and Getters
  };

};

#endif
