// Generated by dia2code
#ifndef TURN__STEP__H
#define TURN__STEP__H


namespace turn {
  class Phase;
}

#include "Phase.h"

namespace turn {

  // interface
  /// class Step - 
  class Step {
    // Associations
    // Setters and Getters
  };

};

#endif
