// Generated by dia2code
#ifndef TURN__TURN__H
#define TURN__TURN__H

#include <vector>
#include <memory>
#include <list>

namespace turn {
  class Phase;
};
namespace state {
  class Player;
}

#include "Phase.h"
#include "state/Player.h"

namespace turn {

  /// class Turn - 
  class Turn {
    // Attributes
  public:
    std::vector<Phase> phases;
    std::weak_ptr<state::Player> activePlayer;
    /// represents that there were n turn before this one
    int iteration;
    std::list<std::weak_ptr<state::Player>> players;
    // Operations
  public:
    void NextPhase ();
    Turn ();
    ~Turn ();
    // Setters and Getters
  };

};

#endif
