// Generated by dia2code
#ifndef TURN__UNTAPSTEP__H
#define TURN__UNTAPSTEP__H


namespace turn {
  class Step;
}

#include "Step.h"

namespace turn {

  /// class UntapStep - 
  class UntapStep : public turn::Step {
    // Operations
  public:
    UntapStep ();
    ~UntapStep ();
    // Setters and Getters
  };

};

#endif
