// Generated by dia2code
#ifndef TURN__UPKEEPSTEP__H
#define TURN__UPKEEPSTEP__H


namespace turn {
  class Step;
}

#include "Step.h"

namespace turn {

  /// class UpkeepStep - 
  class UpkeepStep : public turn::Step {
    // Operations
  public:
    UpkeepStep ();
    ~UpkeepStep ();
    // Setters and Getters
  };

};

#endif
